version: "3.7"

volumes:
  elasticsearch_volume:

services:
  nginx:
    image: nginx:1.17.9-alpine
    logging:
      driver: "fluentd"
      options:
        fluentd-async-connect: "true"
        fluentd-address: localhost:24224
        tag: fluentd

  fluentd:
    #image: fluentd:v1.9.1-1.0
    build:
      context: ./configs/fluentd
    volumes:
      - ./configs/fluentd/plugins:/fluentd/plugins:rw
      - ./configs/fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.9.2
    volumes:
      - ./configs/apm_elastic/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    ports:
      - "8200:8200"

  app:
    build:
      context: ./app
    ports:
      - 8080:8080

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.9.2
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - ./configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
